export enum CharacterSheetPath {
  name = 'name',
  advantageToggle = 'advantageToggle',
  whisperToggle = 'whisperToggle',
  skillSort = 'skillSort',
  profBonus = 'profBonus',
  levels = 'levels',
  spellcastingAbility = 'spellcastingAbility',
  race = 'race',
  background = 'background',
  alignment = 'alignment',
  stats = 'stats',
  savingThrows = 'savingThrows',
  customChecks = 'customChecks',
  otherProficiencies = 'otherProficiencies',
  money = 'money',

  globalAttackModifier = 'globalAttackModifier',
  globalACModifier = 'globalACModifier',
  globalDamageModifier = 'globalDamageModifier',
  features = 'features',
  attacks = 'attacks',
  inventory = 'inventory',
  resources = 'resources',
  skills = 'skills',
}
